version: "3.8"

services:
  # DBX API service with external Redis
  dbx-api:
    # Use published image (replace with your Docker Hub username)
    image: fnlog0/dbx:latest
    # Or build from local Dockerfile
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: dbx-api
    ports:
      - "3000:3000"
    environment:
      # Database configuration - pass your Redis URL here
      - DATABASE_URL=${REDIS_URL:-redis://localhost:6379}
      - DATABASE_TYPE=redis

      # Server configuration
      - HOST=0.0.0.0
      - PORT=3000
      - POOL_SIZE=10
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/redis/admin/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - dbx-network

networks:
  dbx-network:
    driver: bridge
