name: API Tests (Simple)

on:
  push:
    branches: [master]
    paths:
      - "api/**"
      - "crates/**"
  pull_request:
    branches: [master]
    paths:
      - "api/**"
      - "crates/**"

jobs:
  test:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run all tests
        working-directory: api
        run: |
          echo "Running all API tests..."
          cargo test --all-targets --all-features
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          DATABASE_TYPE: redis
          HOST: 127.0.0.1
          PORT: 3000
          POOL_SIZE: 5
          LOG_LEVEL: INFO
          RUST_BACKTRACE: 1

      - name: Run specific test suites
        working-directory: api
        run: |
          echo "Running Redis tests..."
          cargo test --test redis

          echo "Running Redis WebSocket tests..."
          cargo test --test redis_ws

          echo "Running integration tests..."
          cargo test --test integration
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          DATABASE_TYPE: redis
          HOST: 127.0.0.1
          PORT: 3000
          POOL_SIZE: 5
          LOG_LEVEL: INFO
          RUST_BACKTRACE: 1
